### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by Matt-McIntyre**

### CODE REVIEW

**Comment by lexieAA** [comment]
This is a really big pull request next time tried to do pull request more frequently. Overall the changes to your code look a bit cleaner.

**Comment by Matt-McIntyre** [comment]
Are you approving the merge?

**Comment by lexieAA** [comment]
I didn't merge it so that Jason can have it look at it too. I do approve of it.

**Review by jalvesteffer — APPROVED** [review]
The code looks alright from what I can see.  I noticed you have the import org.junit.jupiter.api.Test import in GcFashionApplicationTests.java.  From my experience, using jupiter unit caused issues with the tests being detected in the CI/CD.  Keep that in mind if there are issues with tests.

**Pull request merged**
